language: php

dist: xenial

sudo: false

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer update --no-interaction

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.clover --stop-on-failure
  - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
