language: php

dist: xenial

sudo: false

php:
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit --stop-on-failure
